-- Insert or update ship address data
INSERT INTO public.company_information (
    id,
    company_name,
    address,
    city,
    state,
    postal_code,
    country,
    phone,
    email,
    website,
    ship_to_name,
    ship_to_address,
    ship_to_title,
    ship_to_phone,
    ship_to_email,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    'LANDORA Real Estate Ltd.',
    'Block B, Bashundhara R/A',
    'Dhaka',
    '',
    '1229',
    'Bangladesh',
    '+8801234567890',
    'info@landora.com',
    'www.landora.com',
    'Landora Surjodoy',
    'Block B, Bashundhara R/A, Dhaka 1229',
    'Site Inventory Manager',
    '+8801234567890',
    'inventory@landora.com',
    NOW(),
    NOW()
)
ON CONFLICT (id) DO UPDATE SET
    ship_to_name = EXCLUDED.ship_to_name,
    ship_to_address = EXCLUDED.ship_to_address,
    ship_to_title = EXCLUDED.ship_to_title,
    ship_to_phone = EXCLUDED.ship_to_phone,
    ship_to_email = EXCLUDED.ship_to_email,
    updated_at = NOW();
